# Site settings
title: Francis Baker | Thoughts & Ideas
email: Hi@FPB.im
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://FPB.im" # the base hostname & protocol for your site
twitter_username: frncsbkr
github_username:  Baker

# Build settings
markdown: kramdown
