# Site settings
title: Francis Baker | Thoughts & Ideas
email: Hi@FPB.im
author: Francis Baker
description: > # this means to ignore newlines until "baseurl:"
  With my blog I write about various things about projects I am working on, and things that happened. Understand I break sh*t a lot, it's part of learning. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://FPB.im" # the base hostname & protocol for your site
twitter_username: frncsbkr
github_username:  Baker
linkedin_username: francispbaker

# Build settings
markdown: kramdown
